### ISSUE TITLE
Traitement des infos et intéractions utilisateur

### ISSUE THREAD

**Issue by Angels-dev** [Angels-dev/MultiMinesweeper-Game#7]

**Comment by betasown** [comment]
4fe4161d94fe9a9575cee4bf8ed6097c0979db30 > Manque arrêt du timer, récupération gameStatus, bugs d'affichage à vérifier et victoire à implémenter

**Comment by Angels-dev** [comment]
8b7fe06b37546cebcb4a4ef5be69df9896a7f044
